---

swagger: "2.0"
info:
  title: "HiLink"
  version: "0.1.0"
consumes:
- "application/xml"
produces:
- "application/xml"
schemes:
- "http"
basePath: "/api"
paths:
  /device/autorun-version:
    get:
      operationId: "getDeviceAutoRunVersion"
      tags:
        - "device"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/AutoRunVersion"
  /device/basic_information:
    get:
      operationId: "getDeviceBasicInformation"
      tags:
        - "device"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/DeviceBasicInformation"
  /device/information:
    get:
      operationId: "getDeviceInformation"
      tags:
        - "device"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/DeviceInformation"
  /device/control:
    post:
      operationId: "DeviceControl"
      tags:
        - "device"
      parameters:
        - name: "request"
          in: "body"
          schema:
            type: "object"
            properties:
              Control:
                type: "integer"
                xml:
                  name: "Control"
                enum:
                  - 1 # перезагрузка устройства
                  - 2 # восстановление конфигурации (нет информации о том, как предоставить файлу сохраненную конфигурацию. Возможно, он использует файл http://192.168.8.1/nvram.bak )
                  - 3 # резервное копирование конфигурации (конфигурация доступна по адресу http://192.168.8.1/nvram.bak . Файл с кодировкой base64)
                  - 4 # выключение устройства
      responses:
        200:
          description: "Successful operation"
          schema:
            type: "string"
  /device/signal:
    get:
      operationId: "getDeviceSignal"
      tags:
        - "device"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/DeviceSignal"
  /monitoring/status:
    get:
      operationId: "getMonitoringStatus"
      tags:
      - "monitoring"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/MonitoringStatus"
  /monitoring/traffic-statistics:
    get:
      operationId: "getMonitoringTrafficStatistics"
      tags:
      - "monitoring"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/MonitoringTrafficStatistics"
  /net/current-plmn:
    get:
      operationId: "getCurrentPLMN"
      tags:
        - "net"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/CurrentPLMN"
  /sms/sms-count:
    get:
      operationId: "getSMSCount"
      tags:
        - "sms"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/SMSCount"
  /sms/delete-sms:
    post:
      operationId: "removeSMS"
      tags:
        - "sms"
      parameters:
        - name: "request"
          in: "body"
          schema:
            type: "object"
            properties:
              Index:
                type: "integer"
                xml:
                  name: "Index"
      responses:
        200:
          description: "Successful operation"
          schema:
            type: "string"
  /sms/set-read:
    post:
      operationId: "readSMS"
      tags:
        - "sms"
      parameters:
        - name: "request"
          in: "body"
          schema:
            type: "object"
            properties:
              Index:
                type: "integer"
                xml:
                  name: "Index"
      responses:
        200:
          description: "Successful operation"
          schema:
            type: "string"
  /sms/sms-list:
    post:
      operationId: "getSMSList"
      tags:
        - "sms"
      parameters:
        - name: "request"
          in: "body"
          schema:
            $ref: "#/definitions/SMSListRequest"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/SMSList"
  /ussd/get:
    get:
      operationId: "getUSSD"
      tags:
        - "ussd"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/USSD"
  /ussd/release:
    get:
      operationId: "releaseUSSD"
      tags:
        - "ussd"
      responses:
        200:
          description: "Successful operation"
          schema:
            type: "string"
  /ussd/send:
    post:
      operationId: "sendUSSD"
      tags:
        - "ussd"
      parameters:
        - name: "request"
          in: "body"
          schema:
            $ref: "#/definitions/USSD"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/USSD"
  /ussd/status:
    get:
      operationId: "getUSSDStatus"
      tags:
        - "ussd"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/USSDStatus"
  /webserver/SesTokInfo:
    get:
      operationId: "getWebServerSession"
      tags:
        - "web server"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/SessionToken"
definitions:
  Error:
    type: "object"
    properties:
      code:
        type: "integer"
        xml:
          name: "code"
      message:
        type: "string"
        xml:
          name: "message"
  AutoRunVersion:
    type: "object"
    properties:
      version:
        type: "string"
        xml:
          name: "Version"
  DeviceBasicInformation:
    type: "object"
    properties:
      ProductFamily:
        type: "string"
        xml:
          name: "productfamily"
      Classify:
        type: "string"
        xml:
          name: "classify"
      MultiMode:
        type: "boolean"
        xml:
          name: "multimode"
      RestoreDefaultStatus:
        type: "boolean"
        xml:
          name: "restore_default_status"
      AutoupdateGuideStatus:
        type: "boolean"
        xml:
          name: "autoupdate_guide_status"
      SimSavePinEnable:
        type: "boolean"
        xml:
          name: "sim_save_pin_enable"
      DeviceName:
        type: "string"
        xml:
          name: "devicename"
      SoftwareVersion:
        type: "string"
        xml:
          name: "SoftwareVersion"
      WebUIVersion:
        type: "string"
        xml:
          name: "WebUIVersion"
  DeviceInformation:
    type: "object"
    properties:
      DeviceName:
        type: "string"
        xml:
          name: "DeviceName"
      SerialNumber:
        type: "string"
        xml:
          name: "SerialNumber"
      IMEI:
        type: "string"
        xml:
          name: "Imei"
      IMSI:
        type: "string"
        xml:
          name: "Imsi"
      ICCID:
        type: "string"
        xml:
          name: "Iccid"
      MSISDN:
        type: "string"
        xml:
          name: "Msisdn"
      HardwareVersion:
        type: "string"
        xml:
          name: "HardwareVersion"
      SoftwareVersion:
        type: "string"
        xml:
          name: "SoftwareVersion"
      WebUIVersion:
        type: "string"
        xml:
          name: "WebUIVersion"
      MacAddress1:
        type: "string"
        xml:
          name: "MacAddress1"
      MacAddress2:
        type: "string"
        xml:
          name: "MacAddress2"
      ProductFamily:
        type: "string"
        xml:
          name: "ProductFamily"
      Classify:
        type: "string"
        xml:
          name: "Classify"
      SupportMode:
        type: "string"
        xml:
          name: "supportmode"
      WorkMode:
        type: "string"
        xml:
          name: "workmode"
      WanIPAddress:
        type: "string"
        xml:
          name: "WanIPAddress"
      WanIPv6Address:
        type: "string"
        xml:
          name: "WanIPv6Address"
  DeviceSignal:
    type: "object"
    properties:
      PCI:
        type: "integer"
        xml:
          name: "pci"
      SC:
        type: "integer"
        xml:
          name: "sc"
      CellID:
        type: "integer"
        xml:
          name: "cell_id"
      RSRQ:
        type: "string"
        xml:
          name: "rsrq"
      RSRP:
        type: "string"
        xml:
          name: "rsrp"
      RSSI:
        type: "string"
        xml:
          name: "rssi"
      SINR:
        type: "string"
        xml:
          name: "sinr"
      RSCP:
        type: "string"
        xml:
          name: "rscp"
      ECIO:
        type: "string"
        xml:
          name: "ecio"
      PSATT:
        type: "integer"
        xml:
          name: "psatt"
      Mode:
        type: "integer"
        xml:
          name: "mode"
      LTEBandWidth:
        type: "string"
        xml:
          name: "lte_bandwidth"
      LTEBandInfo:
        type: "string"
        xml:
          name: "lte_bandinfo"
  MonitoringStatus:
    type: "object"
    properties:
      ConnectionStatus:
        type: "integer"
        xml:
          name: "ConnectionStatus"
      WifiConnectionStatus:
        type: "integer"
        xml:
          name: "WifiConnectionStatus"
      SignalStrength:
        type: "integer"
        xml:
          name: "SignalStrength"
      SignalIcon:
        type: "integer"
        xml:
          name: "SignalIcon"
      CurrentNetworkType:
        type: "integer"
        xml:
          name: "CurrentNetworkType"
      CurrentServiceDomain:
        type: "integer"
        xml:
          name: "CurrentServiceDomain"
      RoamingStatus:
        type: "integer"
        xml:
          name: "RoamingStatus"
      BatteryStatus:
        type: "integer"
        xml:
          name: "BatteryStatus"
      BatteryLevel:
        type: "integer"
        xml:
          name: "BatteryLevel"
      BatteryPercent:
        type: "integer"
        xml:
          name: "BatteryPercent"
      SimlockStatus:
        type: "integer"
        xml:
          name: "simlockStatus"
      PrimaryDNS:
        type: "string"
        xml:
          name: "PrimaryDns"
      SecondaryDNS:
        type: "string"
        xml:
          name: "SecondaryDns"
      PrimaryIPv6DNS:
        type: "string"
        xml:
          name: "PrimaryIPv6Dns"
      SecondaryIPv6DNS:
        type: "string"
        xml:
          name: "SecondaryIPv6Dns"
      CurrentWiFiUser:
        type: "integer"
        xml:
          name: "CurrentWifiUser"
      TotalWiFiUser:
        type: "integer"
        xml:
          name: "TotalWifiUser"
      CurrentTotalWiFiuser:
        type: "integer"
        xml:
          name: "currenttotalwifiuser"
      ServiceStatus:
        type: "integer"
        xml:
          name: "ServiceStatus"
      SimStatus:
        type: "integer"
        xml:
          name: "SimStatus"
      WifiStatus:
        type: "integer"
        xml:
          name: "WifiStatus"
      CurrentNetworkTypeEx:
        type: "integer"
        xml:
          name: "CurrentNetworkTypeEx"
      MaxSignal:
        type: "integer"
        xml:
          name: "maxsignal"
      WiFiIndoorOnly:
        type: "integer"
        xml:
          name: "wifiindooronly"
      WiFiFrequence:
        type: "integer"
        xml:
          name: "wififrequence"
      Classify:
        type: "string"
        xml:
          name: "classify"
      FlyMode:
        type: "integer"
        xml:
          name: "flymode"
      CellRoam:
        type: "integer"
        xml:
          name: "cellroam"
      LTECAStatus:
        type: "integer"
        xml:
          name: "ltecastatus"
  MonitoringTrafficStatistics:
    type: "object"
    properties:
      CurrentConnectTime:
        type: "integer"
        xml:
          name: "CurrentConnectTime"
      CurrentUpload:
        type: "integer"
        xml:
          name: "CurrentUpload"
      CurrentDownload:
        type: "integer"
        xml:
          name: "CurrentDownload"
      CurrentDownloadRate:
        type: "integer"
        xml:
          name: "CurrentDownloadRate"
      CurrentUploadRate:
        type: "integer"
        xml:
          name: "CurrentUploadRate"
      TotalUpload:
        type: "integer"
        xml:
          name: "TotalUpload"
      TotalDownload:
        type: "integer"
        xml:
          name: "TotalDownload"
      TotalConnectTime:
        type: "integer"
        xml:
          name: "TotalConnectTime"
      ShowTraffic:
        type: "integer"
        xml:
          name: "showtraffic"
  CurrentPLMN:
    type: "object"
    properties:
      State:
        type: "integer"
        xml:
          name: "State"
      FullName:
        type: "string"
        xml:
          name: "FullName"
      ShortName:
        type: "string"
        xml:
          name: "ShortName"
      Numeric:
        type: "integer"
        xml:
          name: "Numeric"
      Rat:
        type: "integer"
        xml:
          name: "Rat"
  SMSCount:
    type: "object"
    properties:
      LocalUnread:
        type: "integer"
        xml:
          name: "LocalUnread"
      LocalInbox:
        type: "integer"
        xml:
          name: "LocalInbox"
      LocalOutbox:
        type: "integer"
        xml:
          name: "LocalOutbox"
      LocalDraft:
        type: "integer"
        xml:
          name: "LocalDraft"
      LocalDeleted:
        type: "integer"
        xml:
          name: "LocalDeleted"
      SimUnread:
        type: "integer"
        xml:
          name: "SimUnread"
      SimInbox:
        type: "integer"
        xml:
          name: "SimInbox"
      SimOutbox:
        type: "integer"
        xml:
          name: "SimOutbox"
      SimDraft:
        type: "integer"
        xml:
          name: "SimDraft"
      LocalMax:
        type: "integer"
        xml:
          name: "LocalMax"
      SimMax:
        type: "integer"
        xml:
          name: "SimMax"
      SimUsed:
        type: "integer"
        xml:
          name: "SimUsed"
      NewMsg:
        type: "integer"
        xml:
          name: "NewMsg"
  SMSListRequest:
    x-go-type:
      import:
        package: "github.com/kihamo/boggart/components/boggart/providers/hilink/static/models"
        alias: "static"
      type: "SMSListRequest"
    type: "object"
    properties:
      PageIndex:
        type: "integer"
        xml:
          name: "PageIndex"
      ReadCount:
        type: "integer"
        xml:
          name: "ReadCount"
      BoxType:
        type: "integer"
        xml:
          name: "BoxType"
      SortType:
        type: "integer"
        xml:
          name: "SortType"
      Ascending:
        type: "integer"
        xml:
          name: "Ascending"
      UnreadPreferred:
        type: "integer"
        xml:
          name: "UnreadPreferred"
  SMSList:
    type: "object"
    properties:
      Count:
        type: "integer"
        xml:
          name: "Count"
      Messages:
        type: "array"
        xml:
          name: "Messages>Message"
        items:
          type: "object"
          properties:
            Status:
              type: "integer"
              xml:
                name: "Smstat"
            Index:
              type: "integer"
              xml:
                name: "Index"
            Phone:
              type: "string"
              xml:
                name: "Phone"
            Content:
              type: "string"
              xml:
                name: "Content"
            Date:
              type: "string"
              xml:
                name: "Date"
            Sca:
              type: "string"
              xml:
                name: "Sca"
            SaveType:
              type: "integer"
              xml:
                name: "SaveType"
            Priority:
              type: "integer"
              xml:
                name: "Priority"
            SmsType:
              type: "integer"
              xml:
                name: "SmsType"
  USSD:
    type: "object"
    properties:
      Content:
        type: "string"
        xml:
          name: "content"
      CodeType:
        type: "string"
        xml:
          name: "codeType"
      Timeout:
        type: "string"
        xml:
          name: "timeout"
  USSDStatus:
    type: "object"
    properties:
      Result:
        type: "integer"
        xml:
          name: "result"
  SessionToken:
    type: "object"
    properties:
      Session:
        type: "string"
        xml:
          name: "SesInfo"
      Token:
        type: "string"
        xml:
          name: "TokInfo"
