---

swagger: "2.0"
info:
  title: "TVT"
  version: "0.1.0"
consumes:
- "text/xml"
produces:
- "text/xml"
schemes:
- "http"
basePath: "/"
securityDefinitions:
  basicAuth:
    type: "basic"
security:
- basicAuth: []
paths:
  /queryBasicCfg:
    post:
      operationId: "getBasicConfig"
      tags:
      - "information"
      parameters:
      - name: "request"
        in: "body"
        schema:
          $ref: "#/definitions/Request"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/BasicConfig"
        default:
          description: "Unexpected error"
          schema:
            $ref: '#/definitions/Error'

definitions:
  Request:
    type: "object"
  Error:
    type: "object"
    properties:
      status:
        type: "string"
        xml:
          name: "status"
      errorCode:
        type: "integer"
        xml:
          name: "errorCode"
  BasicConfig:
    type: "object"