debug:

substitutions:
  node_name: !secret device_009_node_name
  ip_address: !secret device_009_ip_address

packages:
  common: !include ./_includes/common.yaml
  wifi: !include ./_includes/wifi/home.yaml
  binary_sensor: !include ./_includes/binary_sensor.yaml
  sensor: !include ./_includes/sensor.yaml
  switch: !include ./_includes/switch.yaml
  text_sensor: !include ./_includes/text_sensor.yaml
  time: !include ./_includes/time.yaml

esphome:
  comment: !secret device_009_comment

esp32:
  board: wemos_d1_mini32

external_components:
  - source:
      type: local
      path: ./external_components
  - source: github://oxan/esphome-stream-server

uart:
  id: uart_bus
  baud_rate: 9600
  data_bits: 8
  parity: NONE
  stop_bits: 1
  tx_pin: GPIO17
  rx_pin: GPIO16

stream_server:
  uart_id: uart_bus
  port: 1234

sensor:
  - platform: mercury1
    voltage:
      name: "Voltage"
    amperage:
      name: "Amperage"
    power:
      name: "Power"
    tariff1:
      name: "Tariff 1"
    tariff2:
      name: "Tariff 2"
    tariff3:
      name: "Tariff 3"
    tariff4:
      name: "Tariff 4"
    tariffs_total:
      name: "Tariffs total"
    update_interval: 60s
