substitutions:
  node_name: !secret device_006_node_name
  ip_address: !secret device_006_ip_address

packages:
  common: !include ./_includes/common.yaml
  wifi: !include ./_includes/wifi/home.yaml
  binary_sensor: !include ./_includes/binary_sensor.yaml
  sensor: !include ./_includes/sensor.yaml
  switch: !include ./_includes/switch.yaml
  text_sensor: !include ./_includes/text_sensor.yaml
  time: !include ./_includes/time.yaml

esphome:
  comment: !secret device_006_comment

esp8266:
  board: d1_mini

i2c:
  sda: SDA
  scl: SCL
  scan: True
  id: bus_a

sensor:
  - platform: bme280
    update_interval: 60s
    temperature:
      id: temperature
      name: "Temperature"
      oversampling: 16x
      filters:
        - offset: -2.9
    pressure:
      id: pressure
      name: "Pressure"
    humidity:
      id: humidity
      name: "Humidity"
    address: 0x76