substitutions:
  node_name: !secret device_004_node_name
  ip_address: !secret device_004_ip_address

packages:
  common: !include ./_includes/common.yaml
  wifi: !include ./_includes/wifi/home.yaml
  binary_sensor: !include ./_includes/binary_sensor.yaml
  sensor: !include ./_includes/sensor.yaml
  switch: !include ./_includes/switch.yaml
  text_sensor: !include ./_includes/text_sensor.yaml
  time: !include ./_includes/time.yaml

esphome:
  comment: !secret device_004_comment

esp32:
  board: nodemcu-32s

dallas:
  - pin: GPIO32

binary_sensor:
  - platform: gpio
    id: "aquastorozh_alarm"
    name: "Aquastorozh alarm"
    pin:
      number: GPIO23
      mode: INPUT_PULLUP

  - platform: gpio
    id: "door"
    name: "Entrance door"
    device_class: "door"
    pin:
      number: GPIO4
      mode: INPUT_PULLUP

  - platform: template
    id: kettle_mode
    name: "Kettle Mode"

sensor:
  - platform: dallas
    address: 0xA0000003AF354D28
    name: "Water cold"
  - platform: dallas
    address: 0xC9000003AF6CB128
    name: "Water hot"

  - platform: template
    id: kettle_temp
    name: "Kettle Temp"
    unit_of_measurement: '°C'
    accuracy_decimals: 0
    icon: "mdi:thermometer"
    device_class: "temperature"

  - platform: esp32_hall
    id: "hall"
    name: "ESP32 Hall Sensor"
    update_interval: 60s

#- platform: xiaomi_miscale
#  mac_address: !secret device_004_xiaomi_miscale_mac
#  weight:
#    id: "scale_weight"
#    name: "Scale Weight"
#  impedance:
#    id: "scale_impedance"
#    name: "Scale Impedance"

switch:
  - platform: gpio
    id: "aquastorozh_enabled"
    pin:
      number: GPIO19
      mode: OUTPUT
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      then:
        - delay: 100ms
        - switch.turn_off: aquastorozh_enabled
    internal: true
  - platform: gpio
    id: "aquastorozh_disable"
    pin:
      number: GPIO21
      mode: OUTPUT
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      then:
        - delay: 100ms
        - switch.turn_off: aquastorozh_disable
    internal: true
  - platform: template
    id: "aquastorozh"
    name: "Aquastorozh on/off"
    turn_on_action:
      - switch.turn_on: aquastorozh_enabled
    turn_off_action:
      - switch.turn_on: aquastorozh_disable

  - platform: gpio
    id: "heating_children"
    name: "Heating children room"
    pin:
      number: GPIO27 # relay 1
      mode: OUTPUT
      inverted: true
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: gpio
    id: "heating_bedroom"
    name: "Heating bedroom"
    pin:
      number: GPIO26 # relay 2
      mode: OUTPUT
      inverted: true
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: gpio
    id: "heating_livingroom"
    name: "Heating livingroom"
    pin:
      number: GPIO25 # relay 3
      mode: OUTPUT
      inverted: true
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: gpio
    id: "relay_in_4"
    name: "Relay input 4"
    pin:
      number: GPIO33 # relay 4
      mode: OUTPUT
      inverted: true
    restore_mode: RESTORE_DEFAULT_OFF

#
# BLE
#
# https://github.com/esphome/feature-requests/issues/517
#
# 71 20 83 00 D2 1A C2 82
# 6F 7C B8 09 05 10 02 03
# 39

#
# 15 байт = action IDLE = 0x00, HEATING = 0x01, COOLING = 0x02, KEEP_WARM = 0x03
# 16 байт = Current temperature
# ESP_LOGD("ble_adv", "Response data: %s", hexencode(x).c_str());

#esp32_ble_tracker:
#  scan_parameters:
#    duration: 10s
#    active: false
#  on_ble_service_data_advertise:
#  - mac_address: !secret device_004_xiaomi_kettle_mac
#    service_uuid: FE95
#    then:
#    - lambda: |-
#        id(kettle_temp).publish_state(float(x[16]));
#        if(x[15] == 01) {
#          id(kettle_mode).publish_state(true);
#        } else {
#          id(kettle_mode).publish_state(false);
#        }
