substitutions:
  node_name: !secret device_007_node_name
  ip_address: !secret device_007_ip_address

<<: !include ./_includes/common.yaml
<<: !include ./_includes/wifi/home.yaml

esphome:
  name: ${node_name}
  platform: ESP8266
  board: esp8285
  comment: !secret device_007_comment
  build_path: ./builds/${node_name}

sensor:
- !include _includes/sensor/wifi_signal.yaml
- !include _includes/sensor/uptime.yaml
- !include _includes/sensor/total_daily_energy.yaml
- platform: hlw8012
  sel_pin:
    number: GPIO12
    inverted: true
  cf_pin: GPIO05
  cf1_pin: GPIO14
  current_resistor: 0.00290
  voltage_divider: 940
  current:
    id: "amperage"
    name: "Amperage"
    unit_of_measurement: A
    accuracy_decimals: 3
  voltage:
    id: "voltage"
    name: "Voltage"
    unit_of_measurement: V
  power:
    id: "power"
    name: "Power in watts"
    unit_of_measurement: W
  change_mode_every: 4
  update_interval: 10s

<<: !include ./_includes/text_sensor.yaml

switch:
- !include ./_includes/switch/restart.yaml
- !include ./_includes/switch/shutdown.yaml
- platform: gpio
  pin: GPIO15
  id: "relay"
  name: "Power relay"
  restore_mode: ALWAYS_ON
  on_turn_on:
    - switch.turn_on: led_blue
  on_turn_off:
    - switch.turn_off: led_blue
- platform: gpio
  pin: GPIO02
  inverted: true
  id: "led_blue"
  name: "LED blue"
- platform: gpio
  pin: GPIO00
  inverted: true
  id: "led_red"
  name: "LED red"

binary_sensor:
- !include ./_includes/binary_sensor/status.yaml
- platform: gpio
  pin:
    number: GPIO13
    inverted: true
  id: "button"
  name: "Hardware button"
  on_press:
    - switch.toggle: relay
  internal: true

<<: !include ./_includes/time.yaml