debug:

substitutions:
  node_name: !secret device_009_node_name
  ip_address: !secret device_009_ip_address

packages:
  common: !include ./_includes/common.yaml
  wifi: !include ./_includes/wifi/fazenda.yaml
  binary_sensor: !include ./_includes/binary_sensor.yaml
  sensor: !include ./_includes/sensor.yaml
  switch: !include ./_includes/switch.yaml
  text_sensor: !include ./_includes/text_sensor.yaml
  time: !include ./_includes/time.yaml

esphome:
  comment: !secret device_009_comment

esp32:
  board: wemos_d1_mini32

logger:
  level: VERBOSE

external_components:
  - source:
      type: local
      path: ./external_components
  - source: github://oxan/esphome-stream-server

uart:
  id: uart_bus
  baud_rate: 9600
  data_bits: 8
  parity: NONE
  stop_bits: 1
  tx_pin: GPIO17
  rx_pin: GPIO16

i2c:
  sda: SDA
  scl: SCL
  scan: True
  id: bus_a

stream_server:
  uart_id: uart_bus
  port: 1234

sensor:
  - platform: total_daily_energy
    name: "Total Daily Energy"
    power_id: "power"
  - platform: mercury1
    address: !secret device_009_mercury_address
    update_interval: 60s
    voltage:
      name: "Voltage"
    amperage:
      name: "Amperage"
    power:
      name: "Power"
      id: "power"
    tariff1:
      name: "Tariff 1"
    tariff2:
      name: "Tariff 2"
    tariff3:
      name: "Tariff 3"
    tariff4:
      name: "Tariff 4"
    tariffs_total:
      name: "Tariffs total"

  - platform: bme280
    address: 0x76
    update_interval: 60s
    temperature:
      id: temperature
      name: "Temperature"
      oversampling: 16x
      filters:
        - offset: -2.9
    pressure:
      id: pressure
      name: "Pressure"
    humidity:
      id: humidity
      name: "Humidity"

binary_sensor:
  - platform: gpio
    id: "door"
    name: "Entrance door"
    pin:
      number: GPIO27
