run:
  skip-dirs:
    - test
    - tools
    - docs
    - openhab2
  skip-dirs-use-default: true

linters:
  enable:
    - bodyclose
    - golint
    - interfacer
    - unconvert
    - maligned
    - unparam
    - dogsled
    - nakedret
    - prealloc
    - scopelint
    - gocritic
    - whitespace
    - wsl
  disable:
    - errcheck
