run:
  timeout: 5m
  skip-dirs:
    - test
    - tools
    - docs
    - openhab2
    - components/barcode
  skip-dirs-use-default: true

linters:
  enable:
    - bodyclose
    - golint
    - interfacer
    - unconvert
    - maligned
    - unparam
    - dogsled
    - nakedret
    - prealloc
    - scopelint
    - gocritic
    - whitespace
    # - wsl
    - goprintffuncname
  disable:
    - errcheck
    - gochecknoglobals
    - wsl

linters-settings:
  maligned:
    suggest-new: true