run:
  timeout: 5m
  tests: false
  skip-dirs-use-default: true
  skip-dirs:
    - test
    - tools
    - docs
    - openhab2
    - components/barcode
  skip-files:
    - ".*\\.bindata_assetfs\\.go$"
  allow-parallel-runners: true

linters:
  enable:
    - govet
    - bodyclose
    - unconvert
    - unparam
    - dogsled
    - nakedret
    - prealloc
    - exportloopref
    - gocritic
    - whitespace
    # - wsl
    - goprintffuncname
  disable:
    - errcheck
    - gochecknoglobals
    - wsl

linters-settings:
  maligned:
    suggest-new: true
  govet:
    check-shadowing: true
