---

swagger: "2.0"
info:
  title: "Pantum"
  version: "0.1.0"
consumes:
- "application/json"
produces:
- "application/json"
schemes:
- "http"
basePath: "/"
paths:
  /shtml/omDB.shtml:
    get:
      operationId: "getDatabase"
      tags:
      - "om"
      summary: "Get product info"
      responses:
        200:
          description: "Successful login"
          schema:
            $ref: "#/definitions/Properties"
definitions:
  Properties:
    type: "array"
    items:
      type: "object"
      properties:
        value:
          type: "string"
        name:
          type: "string"
        type:
          type: "string"
        module:
          type: "string"
        index:
          type: "integer"

