---
esphome:
  name: ${node_name}
  build_path: ./builds/${node_name}

web_server:
  port: 80
  include_internal: true
  # https://github.com/esphome/issues/issues/3144
  # js_include: "./_includes/www.js"
  # js_url: ""
  version: 2

prometheus:

logger:
  level: "INFO"
  baud_rate: 0

ota:

debug:
  update_interval: 30s

mqtt:
  broker: !secret home_mqtt_broker
  username: !secret home_mqtt_user
  password: !secret home_mqtt_pssword
  use_abbreviations: false
