---
esphome:
  name: ${node_name}
  build_path: ./builds/${node_name}

web_server:
  port: 80
  include_internal: true

prometheus:

logger:
  level: "DEBUG"
  baud_rate: 0

ota:

mqtt:
  broker: !secret home_mqtt_broker
  username: !secret home_mqtt_user
  password: !secret home_mqtt_pssword
  use_abbreviations: false
