# https://ludeeus.github.io/googledevices/
swagger: "2.0"
info:
  description: "This is an unofficial documentation of the local API used by the Home app to communicate with the device."
  version: "0.0.1"
  title: "Google Home"
  termsOfService: ""
  contact:
    email: "dev@kihamo.ru"
  license:
    name: "MIT"
    url: "https://github.com/rithvikvibhu/GHLocalApi/blob/master/LICENSE.md"
basePath: "/"
tags:
  - name: "info"
    description: "Device Info"
  - name: "settings"
    description: "Device Settings"
  - name: "assistant"
    description: "Assistant"
  - name: "bluetooth"
    description: "Bluetooth"
  - name: "wifi"
    description: "Wifi"
  - name: "static"
    description: "Static Files"
schemes:
  - "http"
paths:
  /setup/eureka_info:
    get:
      tags:
        - "info"
      summary: "This gives most of the device info"
      description: "This gives most of the device info"
      operationId: "getEurekaInfo"
      produces:
        - "application/json"
      parameters:
        - name: "options"
          in: "query"
          description: "Set detail mode"
          required: false
          type: "string"
          enum:
            - "detail"
        - name: "params"
          in: "query"
          description: "Show only params (comma separated)"
          required: false
          type: "string"
          #enum:
          #  - "version"
          #  - "audio"
          #  - "name"
          #  - "build_info"
          #  - "detail"
          #  - "device_info"
          #  - "net"
          #  - "wifi"
          #  - "setup"
          #  - "settings"
          #  - "opt_in"
          #  - "opencast"
          #  - "multizone"
          #  - "proxy"
          #  - "night_mode_params"
          #  - "user_eq"
          #  - "room_equalizer"
      responses:
        200:
          description: "returned device information"
          schema:
            $ref: "#/definitions/EurekaInfo"
  /setup/get_app_device_id:
    post:
      tags:
        - "info"
      summary: "This gives certificate by device ID"
      description: "The app_id in the request is mandatory and refers to Chromecast backdrop/screensaver app. It has to be set to E8C28D3C"
      operationId: "getAppDeviceID"
      parameters:
        - in: "body"
          name: "body"
          description: "Application ID"
          required: true
          schema:
            type: "object"
            properties:
              app_id:
                type: "string"
                enum:
                  - "E8C28D3C"
            required:
              - app_id
      responses:
        200:
          description: "successful operation"
          schema:
            type: "object"
            properties:
              app_device_id:
                type: "string"
              certificate:
                type: "string"
              signed_data:
                type: "string"
            required:
              - app_device_id
              - certificate
              - signed_data
  /setup/offer:
    get:
      tags:
        - "info"
      summary: "This gives a token which is used by the Home app to get offers"
      description: "This gives a token which is used by the Home app to get offers. The offers themselves are not stored on the device. A new token is generated for every request."
      operationId: "getOffer"
      produces:
        - "application/json"
      responses:
        200:
          description: "returned new token"
          schema:
            type: "object"
            properties:
              token:
                type: "string"
            required:
              - token
  /setup/supported_timezones:
    get:
      tags:
        - "info"
      summary: "Simply returns a list of all supported timezones"
      description: "Simply returns a list of all supported timezones"
      operationId: "getSupportedTimezones"
      produces:
        - "application/json"
      responses:
        200:
          description: "returned supported timezones list"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Timezone"
  /setup/supported_locales:
    get:
      tags:
        - "info"
      summary: "Simply returns a list of all supported locales"
      description: "Simply returns a list of all supported locales"
      operationId: "getSupportedLocales"
      produces:
        - "application/json"
      responses:
        200:
          description: "returned supported locales list"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Locale"
  /setup/test_internet_download_speed:
    post:
      tags:
        - "info"
      summary: "This endpoint tests internet download speed"
      description: "This endpoint tests internet download speed. Any sample file URL can be provided."
      operationId: "postTestInternetDownloadSpeed"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "URL for test"
          schema:
            type: "object"
            properties:
              url:
                type: "string"
            required:
              - url
      responses:
        200:
          description: "returned test result"
          schema:
            $ref: "#/definitions/TestInternetDownloadSpeed"
  /setup/set_eureka_info:
    post:
      tags:
        - "settings"
      summary: "This can set custom values to some options"
      description: "Only fields to be modified need to be sent, not all. Sending non-existant fields will still return a 200 OK, but they are not saved."
      operationId: "setEurekaInfo"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "List fields for set"
          required: true
          schema:
            $ref: "#/definitions/SetEurekaInfo"
      responses:
        200:
          description: "successful operation"
definitions:
  EurekaInfo:
    type: "object"
    properties:
      # default
      build_version:
        type: "string"
      cast_build_revision:
        type: "string"
      release_track:
        type: "string"
      uptime:
        type: "number"
        format: "float"
      location:
        "$ref": "#/definitions/Location"
      locale:
        type: "string"
      timezone:
        type: "string"
      time_format:
        type: "integer"
        format: "int64"
      ip_address:
        type: "string"
      mac_address:
        type: "string"
      hotspot_bssid:
        type: "string"
      bssid:
        type: "string"
      ssid:
        type: "string"
      signal_level:
        type: "integer"
        format: "int64"
      wpa_configured:
        type: "boolean"
      wpa_id:
        type: "integer"
        format: "int64"
      wpa_state:
        type: "integer"
        format: "int64"
      tos_accepted:
        type: "boolean"
      noise_level:
        type: "integer"
        format: "int64"
      public_key:
        type: "string"
      ssdp_udn:
        type: "string"
      setup_state:
        type: "integer"
        format: "int64"
      setup_stats:
        $ref: "#/definitions/Stats"
      connected:
        type: "boolean"
      ethernet_connected:
        type: "boolean"
      has_update:
        type: "boolean"
      closed_caption: # XXX: ???
        type: "object"
      # filtered by params
      audio:
        $ref: "#/definitions/Audio"
      build_info:
        $ref: "#/definitions/BuildInfo"
      detail:
        $ref: "#/definitions/Detail"
      device_info:
        $ref: "#/definitions/DeviceInfo"
      multizone:
        $ref: "#/definitions/Multizone"
      name:
        type: "string"
      net:
        $ref: "#/definitions/Net"
      night_mode_params:
        $ref: "#/definitions/NightModeParams"
      opt_in:
        $ref: "#/definitions/OptIn"
      proxy:
        $ref: "#/definitions/Proxy"
      settings:
        $ref: "#/definitions/Settings"
      setup:
        $ref: "#/definitions/Setup"
      user_eq:
        $ref: "#/definitions/UserEq"
      version:
        type: "integer"
        format: "int64"
      wifi:
  Audio:
    type: "object"
    properties:
      digital:
        type: "boolean"
  BuildInfo:
    type: "object"
    properties:
      build_type:
        type: "integer"
        format: "int64"
      cast_build_revision:
        type: "string"
      cast_control_version:
        type: "string"
      preview_channel_state:
        type: "integer"
        format: "int64"
      release_track:
        type: "string"
      system_build_number:
        type: "string"
  Detail:
    type: "object"
    properties:
      icon_list:
        type: "array"
        items:
          $ref: "#/definitions/DetailIconListItem"
      locale:
        $ref: "#/definitions/Locale"
      manufacturer:
        type: "string"
      model_name:
        type: "string"
      timezone:
        $ref: "#/definitions/Timezone"
  DeviceInfo:
    type: "object"
    properties:
      4k_blocked:
        type: "integer"
        format: "int64"
      capabilities:
        type: "object"
        properties:
          aogh_supported:
            type: "boolean"
          assistant_supported:
            type: "boolean"
          audio_hdr_supported:
            type: "boolean"
          audio_surround_mode_supported:
            type: "boolean"
          ble_supported:
            type: "boolean"
          bluetooth_audio_sink_supported:
            type: "boolean"
          bluetooth_audio_source_supported:
            type: "boolean"
          bluetooth_supported:
            type: "boolean"
          cloudcast_supported:
            type: "boolean"
          content_filters_supported:
            type: "boolean"
          display_supported:
            type: "boolean"
          fdr_supported:
            type: "boolean"
          hdmi_prefer_50hz_supported:
            type: "boolean"
          hdmi_prefer_high_fps_supported:
            type: "boolean"
          hotspot_supported:
            type: "boolean"
          https_setup_supported:
            type: "boolean"
          input_management_supported:
            type: "boolean"
          keep_hotspot_until_connected_supported:
            type: "boolean"
          multi_user_supported:
            type: "boolean"
          multizone_supported:
            type: "boolean"
          night_mode_supported:
            type: "boolean"
          night_mode_supported_v2:
            type: "boolean"
          opencast_supported:
            type: "boolean"
          preview_channel_supported:
            type: "boolean"
          reboot_supported:
            type: "boolean"
          remote_ducking_supported:
            type: "boolean"
          setup_supported:
            type: "boolean"
          sleep_mode_supported:
            type: "boolean"
          stats_supported:
            type: "boolean"
          system_sound_effects_supported:
            type: "boolean"
          ui_flipping_supported:
            type: "boolean"
          user_eq_supported:
            type: "boolean"
          wifi_auto_save_supported:
            type: "boolean"
          wifi_regulatory_domain_locked:
            type: "boolean"
          wifi_supported:
            type: "boolean"
      cloud_device_id:
        type: "string"
      factory_country_code:
        type: "string"
      hotspot_bssid:
        type: "string"
      local_authorization_token_hash:
        type: "string"
      mac_address:
        type: "string"
      manufacturer:
        type: "string"
      model_name:
        type: "string"
      product_name:
        type: "string"
      public_key:
        type: "string"
      ssdp_udn:
        type: "string"
      uptime:
        type: "number"
        format: "float"
  Multizone:
    type: "object"
  Net:
    type: "object"
    properties:
      ethernet_connected:
        type: "boolean"
      ip_address:
        type: "string"
      online:
        type: "boolean"
  NightModeParams:
    type: "object"
  OptIn:
    type: "object"
    properties:
      crash:
        type: "boolean"
      opencast:
        type: "boolean"
      stats:
        type: "boolean"
  Proxy:
    type: "object"
    properties:
      mode:
        type: "string"
  Settings:
    type: "object"
    properties:
      closed_caption:
        type: "object"
      control_notifications:
        type: "integer"
        format: "int64"
      country_code:
        type: "string"
      locale:
        type: "string"
      network_standby:
        type: "integer"
        format: "int64"
      system_sound_effects:
        type: "boolean"
      time_format:
        type: "integer"
        format: "int64"
      timezone:
        type: "string"
      wake_on_cast:
        type: "integer"
        format: "int64"
  Setup:
    type: "object"
    properties:
      setup_state:
        type: "integer"
        format: "int64"
      setup_stats:
        $ref: "#/definitions/Stats"
      ssid_suffix:
        type: "string"
      tos_accepted:
        type: "boolean"
  UserEq:
    type: "object"
  Location:
    type: "object"
    properties:
      country_code:
        type: "string"
      latitude:
        type: "number"
        format: "float"
      longitude:
        type: "number"
        format: "float"
  Stats:
    type: "object"
    properties:
      historically_succeeded:
        type: "boolean"
      num_check_connectivity:
        type: "integer"
        format: "int64"
      num_connect_wifi:
        type: "integer"
        format: "int64"
      num_connected_wifi_not_saved:
        type: "integer"
        format: "int64"
      num_initial_eureka_info:
        type: "integer"
        format: "int64"
      num_obtain_ip:
        type: "integer"
        format: "int64"
  DetailIconListItem:
    type: "object"
    properties:
      depth:
        type: "integer"
        format: "int64"
      height:
        type: "integer"
        format: "int64"
      width:
        type: "integer"
        format: "int64"
      mimetype:
        type: "string"
      url:
        type: "string"
  Locale:
    type: "object"
    properties:
      display_string:
        type: "string"
      locale:
        type: "string"
    required:
      - display_string
  Timezone:
    type: "object"
    properties:
      display_string:
        type: "string"
      offset:
        type: "integer"
        format: "int64"
      timezone:
        type: "string"
    required:
      - display_string
      - offset
  TestInternetDownloadSpeed:
    type: "object"
    properties:
      bytes_received:
        type: "integer"
        format: "int64"
      response_code:
        type: "integer"
        format: "int64"
      time_for_data_fetch:
        type: "integer"
        format: "int64"
      time_for_http_response:
        type: "integer"
        format: "int64"
    required:
      - bytes_received
      - response_code
      - time_for_data_fetch
      - time_for_http_response
  SetEurekaInfo:
    type: "object"
    properties:
      name:
        type: "string"
      settings:
        $ref: "#/definitions/Settings"
externalDocs:
  description: "Find out more about Google Home API"
  url: "https://rithvikvibhu.github.io/GHLocalApi/"